application: goprojecteuler
version: 1-1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: present/static/favicon.ico
  upload: present/static/favicon.ico
- url: /static
  static_dir: present/static
  application_readable: true
- url: /.*
  script: _go_app

nobuild_files:
  ^levels/
  ^src